name: Release

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write
  packages: write

jobs:
  build-publish:
    name: Build & Publish Image + Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set version from tag
        id: ver
        run: |
          echo "TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
          echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=raw,value=${{ steps.ver.outputs.VERSION }}
            type=raw,value=latest

      - name: Build & push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: linux/amd64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Create artifact (dist)
        run: |
          mkdir -p dist
          echo "${{ steps.ver.outputs.TAG }}" > dist/VERSION.txt
          tar -czf dist/source-${{ steps.ver.outputs.TAG }}.tar.gz \
            --exclude-vcs --exclude="./logs" --exclude="./backups" .

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: source-${{ steps.ver.outputs.TAG }}
          path: dist/

      - name: Generate release notes
        id: notes
        run: |
          TAG=${{ steps.ver.outputs.TAG }}
          echo "## ${TAG}" > RELEASE_NOTES.md
          if [ -f CHANGELOG.md ]; then
            awk 'BEGIN{p=0}/^## \[/{if(p)exit} $0 ~ TAG{p=1} p' TAG=$TAG CHANGELOG.md >> RELEASE_NOTES.md || true
          fi
          echo "notes<<EOF" >> $GITHUB_OUTPUT
          cat RELEASE_NOTES.md >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.ver.outputs.TAG }}
          name: ${{ steps.ver.outputs.TAG }}
          body: ${{ steps.notes.outputs.notes }}
          draft: false
          prerelease: false
          files: |
            dist/VERSION.txt
            dist/source-${{ steps.ver.outputs.TAG }}.tar.gz
