-- V7 Supabase preparation. Apply with the database migration owner, never a browser key.
-- This creates private, empty tables. It does not switch Flask's storage backend.
BEGIN;
CREATE SCHEMA IF NOT EXISTS v7_private;
REVOKE ALL ON SCHEMA v7_private FROM PUBLIC;
SET LOCAL search_path = v7_private, pg_catalog;

DO $roles$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'v7_backend') THEN
    CREATE ROLE v7_backend NOLOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION NOBYPASSRLS;
  END IF;
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname='v7_backend'
             AND (rolsuper OR rolbypassrls OR rolcreaterole OR rolcreatedb OR rolcanlogin)) THEN
    RAISE EXCEPTION 'Existing v7_backend role has unexpected privileges';
  END IF;
  IF EXISTS (SELECT 1 FROM pg_auth_members m JOIN pg_roles r ON r.oid=m.member WHERE r.rolname='v7_backend') THEN
    RAISE EXCEPTION 'v7_backend must not inherit another role';
  END IF;
END
$roles$;
GRANT USAGE ON SCHEMA v7_private TO v7_backend;
ALTER DEFAULT PRIVILEGES IN SCHEMA v7_private REVOKE ALL ON TABLES FROM PUBLIC;
ALTER DEFAULT PRIVILEGES IN SCHEMA v7_private REVOKE ALL ON SEQUENCES FROM PUBLIC;
ALTER DEFAULT PRIVILEGES IN SCHEMA v7_private REVOKE EXECUTE ON FUNCTIONS FROM PUBLIC;

CREATE TABLE IF NOT EXISTS schema_version (version BIGINT PRIMARY KEY);
CREATE TABLE IF NOT EXISTS tenants (
  tenant TEXT PRIMARY KEY CHECK (tenant ~ '^[A-Za-z0-9][A-Za-z0-9_-]{0,63}$'),
  CHECK (lower(tenant) <> 'versions')
);
CREATE UNIQUE INDEX IF NOT EXISTS tenants_casefold_key ON tenants(lower(tenant));
CREATE TABLE IF NOT EXISTS business_documents (
  tenant TEXT NOT NULL REFERENCES tenants(tenant),
  filename TEXT NOT NULL CHECK (filename ~ '^[A-Za-z0-9][A-Za-z0-9_.-]{0,100}$'),
  payload JSONB NOT NULL, PRIMARY KEY (tenant, filename)
);
CREATE TABLE IF NOT EXISTS document_versions (
  tenant TEXT NOT NULL, day DATE NOT NULL,
  filename TEXT NOT NULL CHECK (filename ~ '^[A-Za-z0-9][A-Za-z0-9_.-]{0,100}$'),
  payload JSONB NOT NULL, PRIMARY KEY (tenant, day, filename)
);
CREATE TABLE IF NOT EXISTS operator_accounts (email TEXT PRIMARY KEY, payload JSONB NOT NULL);
CREATE TABLE IF NOT EXISTS crm_records (tenant TEXT NOT NULL, id TEXT NOT NULL, payload JSONB NOT NULL, PRIMARY KEY(tenant,id));
CREATE TABLE IF NOT EXISTS audit_records (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, payload JSONB NOT NULL);
CREATE TABLE IF NOT EXISTS migration_runs (id TEXT PRIMARY KEY, completed_at TIMESTAMPTZ NOT NULL DEFAULT now(), counts JSONB NOT NULL);
CREATE TABLE IF NOT EXISTS events (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                ts_utc TEXT NOT NULL,
                tenant TEXT NOT NULL,
                channel TEXT NOT NULL,
                session_id TEXT NOT NULL,
                event_type TEXT NOT NULL,
                intent TEXT,
                text TEXT,
                lead_id TEXT,
                message_id TEXT,
                error_code TEXT,
                error_type TEXT,
                meta_json TEXT
            );

CREATE TABLE IF NOT EXISTS leads (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                tenant TEXT NOT NULL,
                lead_id TEXT NOT NULL,
                name TEXT,
                phone TEXT,
                status TEXT DEFAULT 'Open',
                tags TEXT DEFAULT '[]',
                last_session_id TEXT,
                updated_utc TEXT NOT NULL,
                UNIQUE(tenant, lead_id)
            );

CREATE INDEX IF NOT EXISTS idx_events_tenant_ts ON events(tenant, ts_utc);

CREATE INDEX IF NOT EXISTS idx_events_type ON events(event_type);

CREATE INDEX IF NOT EXISTS idx_events_channel ON events(channel);

CREATE INDEX IF NOT EXISTS idx_events_session ON events(session_id);

CREATE INDEX IF NOT EXISTS idx_events_lead_id ON events(lead_id);

CREATE INDEX IF NOT EXISTS idx_events_msgid ON events(message_id);

CREATE INDEX IF NOT EXISTS idx_leads_tenant_updated ON leads(tenant, updated_utc);

CREATE UNIQUE INDEX IF NOT EXISTS uniq_events_dedupe
                ON events(tenant, event_type, message_id)
                WHERE message_id IS NOT NULL AND message_id != '';

CREATE TABLE IF NOT EXISTS management_sessions (token_hash TEXT PRIMARY KEY, identity TEXT NOT NULL, revision TEXT NOT NULL, expires DOUBLE PRECISION NOT NULL);

CREATE TABLE IF NOT EXISTS login_attempts (ip_hash TEXT NOT NULL, attempted DOUBLE PRECISION NOT NULL);

CREATE INDEX IF NOT EXISTS login_attempts_ip ON login_attempts(ip_hash, attempted);

CREATE TABLE IF NOT EXISTS account_authenticators (account TEXT PRIMARY KEY, secret TEXT NOT NULL);

CREATE TABLE IF NOT EXISTS mfa_challenges (token TEXT PRIMARY KEY, account TEXT NOT NULL, identity TEXT NOT NULL, revision TEXT NOT NULL, secret TEXT NOT NULL, enrollment BIGINT NOT NULL, expires DOUBLE PRECISION NOT NULL, attempts BIGINT NOT NULL DEFAULT 0);

CREATE TABLE IF NOT EXISTS managed_businesses (tenant TEXT PRIMARY KEY, owner TEXT);

CREATE TABLE IF NOT EXISTS registration_requests (
        id TEXT PRIMARY KEY, email TEXT NOT NULL, password_hash TEXT NOT NULL,
        kind TEXT NOT NULL, tenant TEXT NOT NULL, business_name TEXT NOT NULL,
        code_hash TEXT NOT NULL, expires DOUBLE PRECISION NOT NULL, attempts BIGINT NOT NULL DEFAULT 0,
        status TEXT NOT NULL, created DOUBLE PRECISION NOT NULL, decided_by TEXT);

CREATE INDEX IF NOT EXISTS registration_email_time ON registration_requests(email,created);

CREATE INDEX IF NOT EXISTS registration_tenant_status ON registration_requests(tenant,status);

CREATE TABLE IF NOT EXISTS billing_contracts (tenant TEXT NOT NULL, kind TEXT NOT NULL, ref TEXT UNIQUE NOT NULL, subscription TEXT, customer TEXT, status TEXT NOT NULL DEFAULT 'not_started', next_due BIGINT, paused BIGINT NOT NULL DEFAULT 0, cancel_at_end BIGINT NOT NULL DEFAULT 0, checkout TEXT, checkout_url TEXT, checkout_expires BIGINT, implementation_paid BIGINT NOT NULL DEFAULT 0, PRIMARY KEY(tenant,kind));

CREATE TABLE IF NOT EXISTS billing_invoices (id TEXT PRIMARY KEY, tenant TEXT NOT NULL, kind TEXT NOT NULL, month TEXT NOT NULL, issued BIGINT NOT NULL, due BIGINT, total BIGINT NOT NULL, paid BIGINT NOT NULL, remaining BIGINT NOT NULL, status TEXT NOT NULL, lines TEXT NOT NULL, url TEXT);

CREATE INDEX IF NOT EXISTS billing_invoice_tenant ON billing_invoices(tenant,issued);

CREATE TABLE IF NOT EXISTS billing_api_charges (tenant TEXT NOT NULL, month TEXT NOT NULL, amount BIGINT NOT NULL, ref TEXT UNIQUE NOT NULL, checkout TEXT, checkout_url TEXT, checkout_expires BIGINT, PRIMARY KEY(tenant,month));

CREATE TABLE IF NOT EXISTS billing_references (ref TEXT PRIMARY KEY, tenant TEXT NOT NULL, kind TEXT NOT NULL);

CREATE TABLE IF NOT EXISTS webhook_inbox (tenant TEXT, provider TEXT, message_id TEXT, state TEXT NOT NULL, updated DOUBLE PRECISION NOT NULL, reply TEXT, PRIMARY KEY (tenant, provider, message_id));

CREATE TABLE IF NOT EXISTS api_usage (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, ts_utc TEXT NOT NULL, tenant TEXT NOT NULL,
        channel TEXT NOT NULL, purpose TEXT NOT NULL, requested_model TEXT NOT NULL,
        model TEXT NOT NULL, status TEXT NOT NULL, input_tokens BIGINT,
        cached_tokens BIGINT, output_tokens BIGINT, cost_nano_usd BIGINT,
        price_version TEXT NOT NULL
    );

CREATE INDEX IF NOT EXISTS idx_api_usage_tenant_ts ON api_usage(tenant, ts_utc);

CREATE INDEX IF NOT EXISTS idx_api_usage_ts ON api_usage(ts_utc);

CREATE TABLE IF NOT EXISTS recorded_sales (
        tenant TEXT NOT NULL, id TEXT NOT NULL, sku TEXT NOT NULL, name TEXT NOT NULL,
        quantity DOUBLE PRECISION NOT NULL CHECK(quantity>0), amount_pence BIGINT NOT NULL CHECK(amount_pence>=0),
        occurred_utc TEXT NOT NULL, channel TEXT NOT NULL, created_utc TEXT NOT NULL,
        voided_utc TEXT, PRIMARY KEY(tenant,id));

CREATE INDEX IF NOT EXISTS idx_recorded_sales_tenant_time ON recorded_sales(tenant,occurred_utc);

CREATE TABLE IF NOT EXISTS inventory_history (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, tenant TEXT NOT NULL, sku TEXT NOT NULL, ts_utc TEXT NOT NULL,
        quantity DOUBLE PRECISION, threshold DOUBLE PRECISION NOT NULL, in_stock BIGINT NOT NULL);

CREATE INDEX IF NOT EXISTS idx_inventory_history_tenant_sku_time ON inventory_history(tenant,sku,ts_utc);

CREATE TABLE IF NOT EXISTS usage_exchange_rate (
            pair TEXT PRIMARY KEY, rate DOUBLE PRECISION NOT NULL, rate_date TEXT NOT NULL);

-- The Data API roles receive no schema/table/function access.
ALTER TABLE schema_version ENABLE ROW LEVEL SECURITY;
ALTER TABLE schema_version FORCE ROW LEVEL SECURITY;
ALTER TABLE tenants ENABLE ROW LEVEL SECURITY;
ALTER TABLE tenants FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS backend_access ON tenants;
CREATE POLICY backend_access ON tenants TO v7_backend USING (tenant = current_setting('v7.tenant', true)) WITH CHECK (tenant = current_setting('v7.tenant', true));
GRANT SELECT, INSERT, UPDATE, DELETE ON tenants TO v7_backend;
ALTER TABLE business_documents ENABLE ROW LEVEL SECURITY;
ALTER TABLE business_documents FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS backend_access ON business_documents;
CREATE POLICY backend_access ON business_documents TO v7_backend USING (tenant = current_setting('v7.tenant', true)) WITH CHECK (tenant = current_setting('v7.tenant', true));
GRANT SELECT, INSERT, UPDATE, DELETE ON business_documents TO v7_backend;
ALTER TABLE document_versions ENABLE ROW LEVEL SECURITY;
ALTER TABLE document_versions FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS backend_access ON document_versions;
CREATE POLICY backend_access ON document_versions TO v7_backend USING (tenant = current_setting('v7.tenant', true)) WITH CHECK (tenant = current_setting('v7.tenant', true));
GRANT SELECT, INSERT, UPDATE, DELETE ON document_versions TO v7_backend;
ALTER TABLE operator_accounts ENABLE ROW LEVEL SECURITY;
ALTER TABLE operator_accounts FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS backend_access ON operator_accounts;
CREATE POLICY backend_access ON operator_accounts TO v7_backend USING (true) WITH CHECK (true);
GRANT SELECT, INSERT, UPDATE, DELETE ON operator_accounts TO v7_backend;
ALTER TABLE crm_records ENABLE ROW LEVEL SECURITY;
ALTER TABLE crm_records FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS backend_access ON crm_records;
CREATE POLICY backend_access ON crm_records TO v7_backend USING (tenant = current_setting('v7.tenant', true)) WITH CHECK (tenant = current_setting('v7.tenant', true));
GRANT SELECT, INSERT, UPDATE, DELETE ON crm_records TO v7_backend;
ALTER TABLE audit_records ENABLE ROW LEVEL SECURITY;
ALTER TABLE audit_records FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS backend_access ON audit_records;
CREATE POLICY backend_access ON audit_records TO v7_backend USING (true) WITH CHECK (true);
GRANT SELECT, INSERT ON audit_records TO v7_backend;
ALTER TABLE migration_runs ENABLE ROW LEVEL SECURITY;
ALTER TABLE migration_runs FORCE ROW LEVEL SECURITY;
ALTER TABLE events ENABLE ROW LEVEL SECURITY;
ALTER TABLE events FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS backend_access ON events;
CREATE POLICY backend_access ON events TO v7_backend USING (tenant = current_setting('v7.tenant', true)) WITH CHECK (tenant = current_setting('v7.tenant', true));
GRANT SELECT, INSERT, UPDATE, DELETE ON events TO v7_backend;
ALTER TABLE leads ENABLE ROW LEVEL SECURITY;
ALTER TABLE leads FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS backend_access ON leads;
CREATE POLICY backend_access ON leads TO v7_backend USING (tenant = current_setting('v7.tenant', true)) WITH CHECK (tenant = current_setting('v7.tenant', true));
GRANT SELECT, INSERT, UPDATE, DELETE ON leads TO v7_backend;
ALTER TABLE management_sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE management_sessions FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS backend_access ON management_sessions;
CREATE POLICY backend_access ON management_sessions TO v7_backend USING (true) WITH CHECK (true);
GRANT SELECT, INSERT, UPDATE, DELETE ON management_sessions TO v7_backend;
ALTER TABLE login_attempts ENABLE ROW LEVEL SECURITY;
ALTER TABLE login_attempts FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS backend_access ON login_attempts;
CREATE POLICY backend_access ON login_attempts TO v7_backend USING (true) WITH CHECK (true);
GRANT SELECT, INSERT, UPDATE, DELETE ON login_attempts TO v7_backend;
ALTER TABLE account_authenticators ENABLE ROW LEVEL SECURITY;
ALTER TABLE account_authenticators FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS backend_access ON account_authenticators;
CREATE POLICY backend_access ON account_authenticators TO v7_backend USING (true) WITH CHECK (true);
GRANT SELECT, INSERT, UPDATE, DELETE ON account_authenticators TO v7_backend;
ALTER TABLE mfa_challenges ENABLE ROW LEVEL SECURITY;
ALTER TABLE mfa_challenges FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS backend_access ON mfa_challenges;
CREATE POLICY backend_access ON mfa_challenges TO v7_backend USING (true) WITH CHECK (true);
GRANT SELECT, INSERT, UPDATE, DELETE ON mfa_challenges TO v7_backend;
ALTER TABLE managed_businesses ENABLE ROW LEVEL SECURITY;
ALTER TABLE managed_businesses FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS backend_access ON managed_businesses;
CREATE POLICY backend_access ON managed_businesses TO v7_backend USING (true) WITH CHECK (true);
GRANT SELECT, INSERT, UPDATE, DELETE ON managed_businesses TO v7_backend;
ALTER TABLE registration_requests ENABLE ROW LEVEL SECURITY;
ALTER TABLE registration_requests FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS backend_access ON registration_requests;
CREATE POLICY backend_access ON registration_requests TO v7_backend USING (true) WITH CHECK (true);
GRANT SELECT, INSERT, UPDATE, DELETE ON registration_requests TO v7_backend;
ALTER TABLE billing_contracts ENABLE ROW LEVEL SECURITY;
ALTER TABLE billing_contracts FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS backend_access ON billing_contracts;
CREATE POLICY backend_access ON billing_contracts TO v7_backend USING (tenant = current_setting('v7.tenant', true)) WITH CHECK (tenant = current_setting('v7.tenant', true));
GRANT SELECT, INSERT, UPDATE, DELETE ON billing_contracts TO v7_backend;
ALTER TABLE billing_invoices ENABLE ROW LEVEL SECURITY;
ALTER TABLE billing_invoices FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS backend_access ON billing_invoices;
CREATE POLICY backend_access ON billing_invoices TO v7_backend USING (tenant = current_setting('v7.tenant', true)) WITH CHECK (tenant = current_setting('v7.tenant', true));
GRANT SELECT, INSERT, UPDATE, DELETE ON billing_invoices TO v7_backend;
ALTER TABLE billing_api_charges ENABLE ROW LEVEL SECURITY;
ALTER TABLE billing_api_charges FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS backend_access ON billing_api_charges;
CREATE POLICY backend_access ON billing_api_charges TO v7_backend USING (tenant = current_setting('v7.tenant', true)) WITH CHECK (tenant = current_setting('v7.tenant', true));
GRANT SELECT, INSERT, UPDATE, DELETE ON billing_api_charges TO v7_backend;
ALTER TABLE billing_references ENABLE ROW LEVEL SECURITY;
ALTER TABLE billing_references FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS backend_access ON billing_references;
CREATE POLICY backend_access ON billing_references TO v7_backend USING (tenant = current_setting('v7.tenant', true)) WITH CHECK (tenant = current_setting('v7.tenant', true));
GRANT SELECT, INSERT, UPDATE, DELETE ON billing_references TO v7_backend;
ALTER TABLE webhook_inbox ENABLE ROW LEVEL SECURITY;
ALTER TABLE webhook_inbox FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS backend_access ON webhook_inbox;
CREATE POLICY backend_access ON webhook_inbox TO v7_backend USING (tenant = current_setting('v7.tenant', true)) WITH CHECK (tenant = current_setting('v7.tenant', true));
GRANT SELECT, INSERT, UPDATE, DELETE ON webhook_inbox TO v7_backend;
ALTER TABLE api_usage ENABLE ROW LEVEL SECURITY;
ALTER TABLE api_usage FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS backend_access ON api_usage;
CREATE POLICY backend_access ON api_usage TO v7_backend USING (tenant = current_setting('v7.tenant', true)) WITH CHECK (tenant = current_setting('v7.tenant', true));
GRANT SELECT, INSERT, UPDATE, DELETE ON api_usage TO v7_backend;
ALTER TABLE recorded_sales ENABLE ROW LEVEL SECURITY;
ALTER TABLE recorded_sales FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS backend_access ON recorded_sales;
CREATE POLICY backend_access ON recorded_sales TO v7_backend USING (tenant = current_setting('v7.tenant', true)) WITH CHECK (tenant = current_setting('v7.tenant', true));
GRANT SELECT, INSERT, UPDATE, DELETE ON recorded_sales TO v7_backend;
ALTER TABLE inventory_history ENABLE ROW LEVEL SECURITY;
ALTER TABLE inventory_history FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS backend_access ON inventory_history;
CREATE POLICY backend_access ON inventory_history TO v7_backend USING (tenant = current_setting('v7.tenant', true)) WITH CHECK (tenant = current_setting('v7.tenant', true));
GRANT SELECT, INSERT, UPDATE, DELETE ON inventory_history TO v7_backend;
ALTER TABLE usage_exchange_rate ENABLE ROW LEVEL SECURITY;
ALTER TABLE usage_exchange_rate FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS backend_access ON usage_exchange_rate;
CREATE POLICY backend_access ON usage_exchange_rate TO v7_backend USING (true) WITH CHECK (true);
GRANT SELECT, INSERT, UPDATE, DELETE ON usage_exchange_rate TO v7_backend;

CREATE TABLE IF NOT EXISTS mcp_grants (digest TEXT PRIMARY KEY, kind TEXT NOT NULL, payload TEXT NOT NULL, expires DOUBLE PRECISION NOT NULL);
CREATE TABLE IF NOT EXISTS mcp_rate (identity TEXT PRIMARY KEY, "window" BIGINT NOT NULL, count BIGINT NOT NULL);
ALTER TABLE mcp_grants ENABLE ROW LEVEL SECURITY;
ALTER TABLE mcp_grants FORCE ROW LEVEL SECURITY;
ALTER TABLE mcp_rate ENABLE ROW LEVEL SECURITY;
ALTER TABLE mcp_rate FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS backend_access ON mcp_grants;
CREATE POLICY backend_access ON mcp_grants TO v7_backend USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS backend_access ON mcp_rate;
CREATE POLICY backend_access ON mcp_rate TO v7_backend USING (true) WITH CHECK (true);
GRANT SELECT, INSERT, UPDATE, DELETE ON mcp_grants, mcp_rate TO v7_backend;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA v7_private TO v7_backend;
REVOKE ALL ON ALL TABLES IN SCHEMA v7_private FROM PUBLIC;
REVOKE ALL ON ALL SEQUENCES IN SCHEMA v7_private FROM PUBLIC;
DO $api_roles$
DECLARE api_role TEXT;
BEGIN
  FOREACH api_role IN ARRAY ARRAY['anon','authenticated','service_role'] LOOP
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname=api_role) THEN
      IF pg_has_role(api_role, 'v7_backend', 'MEMBER') THEN
        RAISE EXCEPTION 'Data API role must not inherit v7_backend';
      END IF;
      EXECUTE format('REVOKE ALL ON SCHEMA v7_private FROM %I', api_role);
      EXECUTE format('REVOKE ALL ON ALL TABLES IN SCHEMA v7_private FROM %I', api_role);
      EXECUTE format('REVOKE ALL ON ALL SEQUENCES IN SCHEMA v7_private FROM %I', api_role);
      EXECUTE format('REVOKE ALL ON ALL FUNCTIONS IN SCHEMA v7_private FROM %I', api_role);
    END IF;
  END LOOP;
END
$api_roles$;
INSERT INTO schema_version VALUES (1) ON CONFLICT DO NOTHING;
COMMIT;
